@echo off
echo Setting up Crowd Flow Optimiser AI Pipeline...
if not exist ".venv\Scripts\python.exe" (
    echo Creating virtual environment...
    python -m venv .venv
)
echo Activating virtual environment...
call .\.venv\Scripts\activate.bat
echo Installing dependencies in venv...
pip install -r requirements.txt
echo Downloading all YOLO, Depth, and Vision Language Models (SmolVLM2)...
python download_models.py
echo Setup complete! You can now run start.bat to launch the server.
