@echo off
echo Setting up Crowd Flow Optimiser AI Pipeline...
if not exist ".venv\Scripts\python.exe" (
    echo Creating virtual environment...
    python -m venv .venv
)
echo Installing dependencies in venv...
.\.venv\Scripts\python.exe -m pip install -r requirements.txt
echo Downloading all YOLO and Depth AI Models...
.\.venv\Scripts\python.exe download_models.py
echo Setup complete! You can now run start.bat to launch the server.
